Repository boocam-project/FastTime-backend, pull requests merged in 2023-11, with the labels that each got.

#114 [refactor] `ArticleUsecase` 리팩토링
  src/main/java/com/fasttime/domain/article/controller/ArticleController.java
  src/main/java/com/fasttime/domain/article/dto/controller/request/ArticleUpdateRequest.java
  src/main/java/com/fasttime/domain/article/dto/service/request/PostLikeServiceDto.java
  src/main/java/com/fasttime/domain/article/dto/service/response/ArticleResponse.java
  src/main/java/com/fasttime/domain/article/exception/ArticleNotFoundException.java
  src/main/java/com/fasttime/domain/article/exception/ArticleReportedException.java
  src/main/java/com/fasttime/domain/article/repository/ArticleRepository.java
  src/main/java/com/fasttime/domain/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/fasttime/domain/article/repository/ArticleRepositoryImpl.java
  src/main/java/com/fasttime/domain/article/service/ArticleCommandService.java
  src/main/java/com/fasttime/domain/article/service/ArticleQueryService.java
  src/main/java/com/fasttime/domain/article/service/usecase/ArticleCommandUseCase.java
  src/main/java/com/fasttime/domain/article/service/usecase/ArticleQueryUseCase.java
  src/main/java/com/fasttime/domain/record/service/RecordService.java
  src/test/java/com/fasttime/domain/article/docs/ArticleControllerDocsTest.java
  src/test/java/com/fasttime/domain/article/unit/service/ArticleCommandServiceTest.java
  src/test/java/com/fasttime/domain/article/unit/service/ArticleQueryServiceTest.java
  src/test/java/com/fasttime/domain/member/docs/AdminControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Labels: 🚧 refactoring

#115 [refactor] `ReportStatus` Renaming
  src/main/java/com/fasttime/domain/article/entity/Article.java
  src/main/java/com/fasttime/domain/article/entity/ReportStatus.java
  src/main/java/com/fasttime/domain/article/exception/BadArticleReportStatusException.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/main/java/com/fasttime/domain/report/service/ReportService.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/test/java/com/fasttime/domain/article/unit/entity/PostTest.java
  src/test/java/com/fasttime/domain/article/unit/repository/ArticleRepositoryTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
  src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
Labels: 🚧 refactoring

#116 [refactor] 게시글 신고 기능 추출
  src/main/java/com/fasttime/domain/article/service/ArticleReportService.java
  src/main/java/com/fasttime/domain/article/service/usecase/ArticleReportUseCase.java
  src/test/java/com/fasttime/domain/article/unit/service/ArticleReportServiceTest.java
Labels: 🚧 refactoring

#117 [feat] 외부 주입 프로퍼티 Provider 제공
  src/main/java/com/fasttime/domain/article/service/ArticleSettingProvider.java
Labels: 🛠️ feature

#118 댓글 전체적인 기능 수정 및 리팩토링
  src/docs/asciidoc/comment/comment-api.adoc
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
  src/main/java/com/fasttime/domain/comment/dto/request/CreateCommentRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/request/DeleteCommentRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/request/GetCommentsRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/request/UpdateCommentRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/com/fasttime/domain/comment/dto/response/PostCommentResponseDTO.java
  src/main/java/com/fasttime/domain/comment/entity/Comment.java
  src/main/java/com/fasttime/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/fasttime/domain/comment/repository/CommentCustomRepository.java
  src/main/java/com/fasttime/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/comment/repository/CommentRepository.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
  src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
Labels: 📕 document, 🛠️ feature, 🚧 refactoring

#119 댓글 작성자만 댓글 수정 삭제할 수 있도록 수정
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
  src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java
  src/main/java/com/fasttime/domain/comment/exception/NotCommentAuthorException.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
Labels: 👷‍♂️fix

#122 댓글 페이징 기능 수정 및 리팩토링
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
  src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java
  src/main/java/com/fasttime/domain/comment/dto/request/CommentPageRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/request/GetCommentsRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/response/CommentListResponseDTO.java
  src/main/java/com/fasttime/domain/comment/entity/Comment.java
  src/main/java/com/fasttime/domain/comment/exception/MultipleSearchConditionException.java
  src/main/java/com/fasttime/domain/comment/repository/CommentCustomRepository.java
  src/main/java/com/fasttime/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/resources/application.yaml
  src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring
