Repository boocam-project/FastTime-backend, pull requests merged in 2023-12, with the labels that each got.

#128 [fix] MemberControllerTest에서 발생하는 컴파일 에러를 수정한다.
  src/test/java/com/fasttime/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/MemberControllerTest.java
  src/test/java/com/fasttime/util/ControllerUnitTestSupporter.java
Labels: 👷‍♂️fix

#135 Record 도메인 이름변경 및, 레디스 환경 셋팅
  build.gradle
  docker-compose.yaml
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/record/record-api.adoc
  src/main/java/com/fasttime/FastTimeApplication.java
  src/main/java/com/fasttime/domain/article/entity/Article.java
  src/main/java/com/fasttime/domain/memberArticleLike/controller/MemberArticleLikeRestController.java
  src/main/java/com/fasttime/domain/memberArticleLike/controller/MemberArticleLikeRestControllerAdvice.java
  src/main/java/com/fasttime/domain/memberArticleLike/dto/MemberArticleLikeDTO.java
  src/main/java/com/fasttime/domain/memberArticleLike/dto/request/CreateMemberArticleLikeRequestDTO.java
  src/main/java/com/fasttime/domain/memberArticleLike/dto/request/DeleteMemberArticleLikeRequestDTO.java
  src/main/java/com/fasttime/domain/memberArticleLike/entity/MemberArticleLike.java
  src/main/java/com/fasttime/domain/memberArticleLike/exception/AlreadyExistsMemberArticleLikeException.java
  src/main/java/com/fasttime/domain/memberArticleLike/exception/DuplicateMemberArticleLikeException.java
  src/main/java/com/fasttime/domain/memberArticleLike/exception/MemberArticleLikeNotFoundException.java
  src/main/java/com/fasttime/domain/memberArticleLike/repository/MemberArticleLikeRepository.java
  src/main/java/com/fasttime/domain/memberArticleLike/service/MemberArticleLikeService.java
  src/main/java/com/fasttime/domain/record/controller/RecordRestController.java
  src/main/java/com/fasttime/domain/record/entity/Record.java
  src/main/java/com/fasttime/domain/record/repository/RecordRepository.java
  src/main/java/com/fasttime/domain/record/service/RecordService.java
  src/main/java/com/fasttime/global/config/ApplicationEnvConfig.java
  src/main/java/com/fasttime/global/config/RedisConfig.java
  src/main/java/com/fasttime/global/config/ThreadConfig.java
  src/main/resources/.env
  src/test/java/com/fasttime/domain/memberArticleLike/docs/MemberArticleLikeControllerDocsTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/controller/MemberArticleLikeRestControllerTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/entity/MemberArticleLikeTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/service/MemberArticleLikeServiceTest.java
  src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Labels: 🚧 refactoring

#136 미처 변경하지 못한 post 변수들을 article로 변경합니다.
  .env
  src/main/java/com/fasttime/domain/article/controller/ArticleController.java
  src/main/java/com/fasttime/domain/article/service/ArticleCommandService.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/main/java/com/fasttime/domain/member/controller/AdminController.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/main/java/com/fasttime/domain/memberArticleLike/controller/MemberArticleLikeRestController.java
  src/main/java/com/fasttime/domain/memberArticleLike/dto/MemberArticleLikeDTO.java
  src/main/java/com/fasttime/domain/memberArticleLike/dto/request/CreateMemberArticleLikeRequestDTO.java
  src/main/java/com/fasttime/domain/memberArticleLike/dto/request/DeleteMemberArticleLikeRequestDTO.java
  src/main/java/com/fasttime/domain/memberArticleLike/entity/MemberArticleLike.java
  src/main/java/com/fasttime/domain/memberArticleLike/repository/MemberArticleLikeRepository.java
  src/main/java/com/fasttime/domain/memberArticleLike/service/MemberArticleLikeService.java
  src/main/java/com/fasttime/domain/report/dto/ReportDTO.java
  src/main/java/com/fasttime/domain/report/dto/request/CreateReportRequestDTO.java
  src/main/java/com/fasttime/domain/report/entity/Report.java
  src/main/java/com/fasttime/domain/report/repository/ReportRepository.java
  src/main/java/com/fasttime/domain/report/service/ReportService.java
  src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java
  src/test/java/com/fasttime/FastTimeApplicationTests.java
  src/test/java/com/fasttime/domain/article/unit/controller/ArticleControllerTest.java
  src/test/java/com/fasttime/domain/article/unit/entity/PostTest.java
  src/test/java/com/fasttime/domain/article/unit/repository/ArticleRepositoryTest.java
  src/test/java/com/fasttime/domain/article/unit/service/ArticleCommandServiceTest.java
  src/test/java/com/fasttime/domain/article/unit/service/ArticleQueryServiceTest.java
  src/test/java/com/fasttime/domain/article/unit/service/ArticleReportServiceTest.java
  src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/comment/unit/entity/CommentTest.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
  src/test/java/com/fasttime/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/MemberControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/docs/MemberArticleLikeControllerDocsTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/controller/MemberArticleLikeRestControllerTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/entity/MemberArticleLikeTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/service/MemberArticleLikeServiceTest.java
  src/test/java/com/fasttime/domain/report/docs/ReportControllerDocsTest.java
  src/test/java/com/fasttime/domain/report/unit/controller/ReportRestControllerTest.java
  src/test/java/com/fasttime/domain/report/unit/entity/ReportTest.java
  src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
  src/test/java/com/fasttime/util/ControllerUnitTestSupporter.java
Labels: 🚧 refactoring

#137 비동기 작업 가상스레드로 수행되는지 확인하는 테스트코드 작성.
  src/test/java/com/fasttime/global/config/ThreadConfigTest.java
Labels: 🚧 refactoring

#141 JWT 리팩토링
  src/main/java/com/fasttime/domain/member/service/MemberService.java
  src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java
  src/main/java/com/fasttime/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/fasttime/global/jwt/JwtPayload.java
  src/main/java/com/fasttime/global/jwt/JwtProvider.java
Labels: 🚧 refactoring

#142 [refactor] : 개발서버 전용 cors filter 추가
  src/main/java/com/fasttime/global/config/CorsConfig.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
Labels: 🛠️ feature

#144 [fix] : 테스트 의존성 수정
  src/main/java/com/fasttime/domain/member/entity/RefreshToken.java
  src/main/java/com/fasttime/domain/report/repository/ReportRepository.java
  src/main/java/com/fasttime/domain/report/service/ReportService.java
  src/main/java/com/fasttime/global/config/EmailConfig.java
  src/test/java/com/fasttime/domain/article/unit/controller/ArticleControllerTest.java
  src/test/java/com/fasttime/domain/article/unit/repository/ArticleRepositoryTest.java
  src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/member/controller/EmailControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/controller/MemberArticleLikeRestControllerTest.java
  src/test/java/com/fasttime/domain/report/unit/controller/ReportRestControllerTest.java
  src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
  src/test/java/com/fasttime/util/ControllerUnitTestSupporter.java
  src/test/resources/application.yaml
Labels: 👷‍♂️fix

#145 [fix] : MemberServiceTest 컴파일 에러 수정
  src/main/java/com/fasttime/global/config/CorsConfig.java
  src/main/java/com/fasttime/global/config/CorsProperties.java
  src/test/java/com/fasttime/domain/member/unit/service/MemberServiceTest.java
  src/test/resources/application.yaml
Labels: 👷‍♂️fix

#149 [refactor] : 로컬 테스트 이메일 서비스 분리
  src/main/java/com/fasttime/domain/member/controller/EmailController.java
  src/main/java/com/fasttime/domain/member/service/EmailUseCase.java
  src/main/java/com/fasttime/domain/member/service/LocalEmailService.java
  src/main/java/com/fasttime/domain/member/service/ProdEmailService.java
  src/main/java/com/fasttime/global/config/EmailConfig.java
  src/test/java/com/fasttime/util/ControllerUnitTestSupporter.java
Labels: 🚧 refactoring

#150 [fix] : 이메일 테스트코드 수정
  src/main/java/com/fasttime/domain/member/controller/EmailController.java
  src/main/java/com/fasttime/domain/member/dto/request/EmailRequest.java
  src/main/java/com/fasttime/domain/member/service/LocalEmailService.java
  src/main/java/com/fasttime/domain/member/service/ProdEmailService.java
  src/test/java/com/fasttime/domain/member/controller/EmailControllerTest.java
Labels: 👷‍♂️fix

#151 [fix] 게시글 좋아요/싫어요 테스트 수정
  src/test/java/com/fasttime/domain/memberArticleLike/docs/MemberArticleLikeControllerDocsTest.java
  src/test/java/com/fasttime/domain/memberArticleLike/unit/controller/MemberArticleLikeRestControllerTest.java
Labels: 👷‍♂️fix

#154 [feat] : Article CommentCount Update Event 생성
  src/main/java/com/fasttime/domain/article/dto/service/response/ArticlesResponse.java
  src/main/java/com/fasttime/domain/article/entity/Article.java
  src/main/java/com/fasttime/domain/article/repository/ArticleQueryResponse.java
  src/main/java/com/fasttime/domain/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/fasttime/domain/article/repository/ArticleRepositoryImpl.java
  src/main/java/com/fasttime/domain/article/service/ArticleEventListener.java
  src/main/java/com/fasttime/domain/article/service/ArticleQueryService.java
  src/main/java/com/fasttime/domain/article/service/usecase/ArticleQueryUseCase.java
  src/main/java/com/fasttime/domain/comment/infra/CommentCreateEvent.java
  src/main/java/com/fasttime/domain/comment/infra/CommentDeleteEvent.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/test/java/com/fasttime/domain/article/unit/repository/ArticleRepositoryTest.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
  src/test/java/com/fasttime/util/fixture/ArticleFixture.java
Labels: 🛠️ feature

#157 Flyway 적용 및 마이그레이션 프로필 변경, ColumnDefinition 추가
  build.gradle
  docker-compose.yaml
  src/main/java/com/fasttime/domain/article/entity/Article.java
  src/main/java/com/fasttime/domain/article/entity/ArticleContent.java
  src/main/java/com/fasttime/domain/member/entity/Member.java
  src/main/java/com/fasttime/domain/member/service/LocalEmailService.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__Add_member_table.sql
  src/main/resources/db/migration/V3__Add_admin_table.sql
  src/main/resources/db/migration/V4__Add_adminEmail_table.sql
  src/main/resources/db/migration/V5__Add_article_table.sql
  src/main/resources/db/migration/V6__Add_comment_table.sql
  src/main/resources/db/migration/V7__Add_memberArticleLike_table.sql
  src/main/resources/db/migration/V8__Add_refreshToken_table.sql
  src/main/resources/db/migration/V9__Add_report_table.sql
  src/test/resources/application.yaml
Labels: 🐞 bug, 🛠️ feature, 👷‍♂️fix

#166 엔드포인트 수정(Restful 기반) 및 테스트코드 엔드포인트 수정
  src/main/java/com/fasttime/domain/member/controller/AdminController.java
  src/main/java/com/fasttime/domain/member/controller/MemberController.java
  src/test/java/com/fasttime/domain/member/docs/AdminControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/MemberControllerTest.java
Labels: 🚧 refactoring

#153 [feature] Review, Tag 엔터티 추가
  src/main/java/com/fasttime/domain/review/entity/Review.java
  src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
  src/main/java/com/fasttime/domain/review/entity/Tag.java
  src/main/resources/db/migration/V10__Add_review_table.sql
  src/main/resources/db/migration/V11__Add_tag_table.sql
  src/main/resources/db/migration/V12__Add_reviewtag_table.sql
Labels: 🛠️ feature, 🚧 refactoring

#168 [fix] : 잘못된 flyway sql version fix
  src/main/resources/db/migration/V11__Add_tag_table.sql
  src/main/resources/db/migration/V12__Add_reviewtag_table.sql
  src/main/resources/db/migration/V13__Add_Column_review_table.sql
Labels: 👷‍♂️fix

#173 [fix] 엔드포인트 변경으로 인한 security 오류 수정
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
Labels: 👷‍♂️fix

#169 [fix] 댓글 adoc 파일 수정
  src/docs/asciidoc/comment/comment-api.adoc
Labels: 👷‍♂️fix

#174 [fix] 댓글 등록 500 에러 해결
  src/main/java/com/fasttime/domain/article/service/ArticleEventListener.java
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
Labels: 👷‍♂️fix
