Repository boocam-project/FastTime-backend, pull requests merged in 2023-10, with the labels that each got.

#47 login Response 수정
  src/main/java/com/fasttime/domain/member/controller/MemberController.java
  src/main/java/com/fasttime/domain/member/response/MemberResponse.java
  src/main/java/com/fasttime/domain/member/service/MemberService.java
  src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
  src/test/java/com/fasttime/domain/member/service/MemberServiceTestForAuto.java
Labels: 👷‍♂️fix

#49 [fix] WebConfig 수정
  src/main/java/com/fasttime/global/config/WebConfig.java
Labels: 👷‍♂️fix

#48 [feat] 게시글 댓글 조회 API 구현
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/test/java/com/fasttime/domain/comment/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring

#56 [fix] 로그인 인터셉터 수정
  src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java
  src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
Labels: 👷‍♂️fix

#58 [fix] PasswordEncoder 코드 변경
  src/main/java/com/fasttime/global/config/PasswordEncoderConfig.java
Labels: 👷‍♂️fix

#57 [fix] 회원 닉네임을 포함한 댓글 데이터를 응답하도록 수정
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
  src/main/java/com/fasttime/domain/comment/dto/response/MyPageCommentResponseDTO.java
  src/main/java/com/fasttime/domain/comment/dto/response/PostCommentResponseDTO.java
  src/main/java/com/fasttime/domain/comment/entity/Comment.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/test/java/com/fasttime/domain/comment/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring, 👷‍♂️fix

#64 [feat] 댓글 Spring REST Docs 도입
  src/docs/asciidoc/comment/comment-api.adoc
  src/docs/asciidoc/post/post-api.adoc
  src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/comment/unit/entity/CommentTest.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
Labels: 📕 document, 🛠️ feature

#68 [feat] 신고 Spring API Docs 도입
  src/docs/asciidoc/report/report-api.adoc
  src/main/java/com/fasttime/domain/report/contoller/ReportRestController.java
  src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/report/docs/ReportControllerDocsTest.java
  src/test/java/com/fasttime/domain/report/unit/controller/ReportRestControllerTest.java
  src/test/java/com/fasttime/domain/report/unit/entity/ReportTest.java
  src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
Labels: 📕 document, 🛠️ feature

#69 Admin, Member Spring Rest Docs 도입 및 리팩토링
  src/docs/asciidoc/admin/admin-api.adoc
  src/docs/asciidoc/member/member-api.adoc
  src/main/java/com/fasttime/domain/member/controller/AdminController.java
  src/main/java/com/fasttime/domain/member/controller/EmailController.java
  src/main/java/com/fasttime/domain/member/controller/MemberController.java
  src/main/java/com/fasttime/domain/member/request/CodeRequest.java
  src/main/java/com/fasttime/domain/member/request/RePasswordRequest.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/main/java/com/fasttime/domain/member/service/MemberService.java
  src/main/java/com/fasttime/global/config/WebConfig.java
  src/main/java/com/fasttime/global/interceptor/AdminCheckInterceptor.java
  src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java
  src/test/java/com/fasttime/domain/member/docs/AdminControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/MemberControllerTestForAuto.java
  src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
  src/test/java/com/fasttime/domain/member/unit/service/MemberServiceTestForAuto.java
Labels: 📕 document, 🛠️ feature, 🚧 refactoring

#70 [fix] CORS 관련 설정 수정
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/config/WebConfig.java
Labels: 👷‍♂️fix

#73 [fix] 게시글 DTO 에 createdAt, updatedAt 필드를 추가한다.
  src/main/java/com/fasttime/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/fasttime/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/fasttime/domain/post/service/PostQueryService.java
Labels: 👷‍♂️fix

#76 [feat] 게시글 좋아요/싫어요 API 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/record/record-api.adoc
  src/main/java/com/fasttime/domain/record/controller/RecordRestController.java
  src/main/java/com/fasttime/domain/record/controller/RecordRestControllerAdvice.java
  src/main/java/com/fasttime/domain/record/dto/RecordDTO.java
  src/main/java/com/fasttime/domain/record/dto/request/CreateRecordRequestDTO.java
  src/main/java/com/fasttime/domain/record/dto/request/DeleteRecordRequestDTO.java
  src/main/java/com/fasttime/domain/record/entity/Record.java
  src/main/java/com/fasttime/domain/record/exception/DuplicateRecordException.java
  src/main/java/com/fasttime/domain/record/exception/RecordNotFoundException.java
  src/main/java/com/fasttime/domain/record/service/RecordService.java
  src/test/java/com/fasttime/domain/record/docs/RecordControllerDocsTest.java
  src/test/java/com/fasttime/domain/record/unit/controller/RecordRestControllerTest.java
  src/test/java/com/fasttime/domain/record/unit/entity/RecordTest.java
  src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Labels: 📕 document, 🛠️ feature, ❗️suggestion

#78 [feat] 게시글 좋아요/싫어요 합계 수정 로직 추가
  src/main/java/com/fasttime/domain/record/service/RecordService.java
  src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Labels: 🛠️ feature

#81 [feat] 게시글 좋아요/싫어요 조회 기능 추가
  src/main/java/com/fasttime/domain/record/repository/RecordRepository.java
  src/main/java/com/fasttime/domain/record/service/RecordService.java
  src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Labels: 🛠️ feature, 👷‍♂️fix

#82 [feature] 이메일 전송 enable
  .gitignore
  src/main/java/com/fasttime/domain/member/service/EmailService.java
  src/main/java/com/fasttime/global/config/EmailConfig.java
  src/main/resources/application.yaml
  src/test/java/com/fasttime/util/FakeEmailConfig.java
  src/test/resources/application.yaml
Labels: 🛠️ feature

#83 [refactor] 게시글 dto 이동
  src/main/java/com/fasttime/domain/post/controller/PostController.java
  src/main/java/com/fasttime/domain/post/dto/service/request/PostCreateServiceDto.java
  src/main/java/com/fasttime/domain/post/dto/service/request/PostDeleteServiceDto.java
  src/main/java/com/fasttime/domain/post/dto/service/request/PostUpdateServiceDto.java
  src/main/java/com/fasttime/domain/post/service/PostCommandService.java
  src/main/java/com/fasttime/domain/post/service/PostCommandUseCase.java
  src/test/java/com/fasttime/domain/member/docs/AdminControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
  src/test/java/com/fasttime/domain/post/docs/PostControllerDocsTest.java
  src/test/java/com/fasttime/domain/post/unit/controller/PostControllerTest.java
  src/test/java/com/fasttime/domain/post/unit/service/PostCommandServiceTest.java
Labels: 🚧 refactoring

#84 [fix] 댓글 삭제 기능 수정
  src/main/java/com/fasttime/domain/comment/entity/Comment.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/test/java/com/fasttime/domain/comment/unit/entity/CommentTest.java
Labels: 👷‍♂️fix

#87 [fix] anonymity 수정
  src/main/java/com/fasttime/domain/post/service/PostCommandService.java
Labels: 👷‍♂️fix

#88 [fix] 댓글 삭제 수정
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
Labels: 👷‍♂️fix

#89 [refactor] 신고 기능 리팩토링
  src/main/java/com/fasttime/domain/report/contoller/ReportRestController.java
  src/main/java/com/fasttime/domain/report/contoller/ReportRestControllerAdvice.java
  src/main/java/com/fasttime/domain/report/dto/request/CreateReportRequestDTO.java
  src/main/java/com/fasttime/domain/report/entity/Report.java
  src/main/java/com/fasttime/domain/report/exception/AlreadyDeletedPostException.java
  src/main/java/com/fasttime/domain/report/exception/DuplicateReportException.java
  src/main/java/com/fasttime/domain/report/service/ReportService.java
  src/test/java/com/fasttime/domain/report/docs/ReportControllerDocsTest.java
  src/test/java/com/fasttime/domain/report/unit/controller/ReportRestControllerTest.java
  src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
Labels: 🚧 refactoring

#90 [refactor] 좋아요/싫어요 기능 리팩토링
  src/docs/asciidoc/record/record-api.adoc
  src/main/java/com/fasttime/domain/record/controller/RecordRestController.java
  src/main/java/com/fasttime/domain/record/controller/RecordRestControllerAdvice.java
  src/main/java/com/fasttime/domain/record/dto/request/CreateRecordRequestDTO.java
  src/main/java/com/fasttime/domain/record/dto/request/DeleteRecordRequestDTO.java
  src/main/java/com/fasttime/domain/record/exception/AlreadyExistsRecordException.java
  src/main/java/com/fasttime/domain/record/exception/DuplicateRecordException.java
  src/main/java/com/fasttime/domain/record/repository/RecordRepository.java
  src/main/java/com/fasttime/domain/record/service/RecordService.java
  src/test/java/com/fasttime/domain/record/docs/RecordControllerDocsTest.java
  src/test/java/com/fasttime/domain/record/unit/controller/RecordRestControllerTest.java
  src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Labels: 🚧 refactoring

#91 [refactor] 댓글 기능 리팩토링
  src/docs/asciidoc/comment/comment-api.adoc
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
  src/main/java/com/fasttime/domain/comment/dto/request/CreateCommentRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/request/DeleteCommentRequestDTO.java
  src/main/java/com/fasttime/domain/comment/dto/request/UpdateCommentRequestDTO.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
Labels: 🚧 refactoring

#93 [feat] Logback 추가
  .gitignore
  build.gradle
  src/main/resources/logback/appender/logback-console.xml
  src/main/resources/logback/appender/logback-dev.xml
  src/main/resources/logback/appender/logback-local.xml
  src/main/resources/logback/appender/logback-prod.xml
  src/main/resources/logback/logback-spring.xml
Labels: 🛠️ feature

#92 게시글 서비스 리팩토링
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/main/java/com/fasttime/domain/post/controller/PostController.java
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/main/java/com/fasttime/domain/post/exception/PostDeletedException.java
  src/main/java/com/fasttime/domain/post/exception/PostReportedException.java
  src/main/java/com/fasttime/domain/post/repository/PostRepository.java
  src/main/java/com/fasttime/domain/post/service/PostCommandService.java
  src/main/java/com/fasttime/domain/post/service/PostQueryService.java
  src/main/java/com/fasttime/domain/post/service/PostQueryUseCase.java
  src/main/java/com/fasttime/domain/record/service/RecordService.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
  src/test/java/com/fasttime/domain/member/docs/AdminControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
  src/test/java/com/fasttime/domain/post/docs/PostControllerDocsTest.java
  src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
  src/test/java/com/fasttime/domain/post/unit/service/PostCommandServiceTest.java
  src/test/java/com/fasttime/domain/post/unit/service/PostQueryServiceTest.java
  src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Labels: 🚧 refactoring, 👷‍♂️fix

#97 [refactor] 서버 log 메시지, httpResponse 메시지 분리
  src/main/java/com/fasttime/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/fasttime/domain/member/exception/AdminNotFoundException.java
  src/main/java/com/fasttime/domain/member/exception/UserNotFoundException.java
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/main/java/com/fasttime/domain/post/exception/NotPostWriterException.java
  src/main/java/com/fasttime/domain/post/exception/PostDeletedException.java
  src/main/java/com/fasttime/domain/post/exception/PostNotFoundException.java
  src/main/java/com/fasttime/domain/post/exception/PostReportedException.java
  src/main/java/com/fasttime/domain/post/service/PostCommandService.java
  src/main/java/com/fasttime/domain/post/service/PostQueryService.java
  src/main/java/com/fasttime/domain/record/exception/AlreadyExistsRecordException.java
  src/main/java/com/fasttime/domain/record/exception/DuplicateRecordException.java
  src/main/java/com/fasttime/domain/record/exception/RecordNotFoundException.java
  src/main/java/com/fasttime/domain/report/contoller/ReportRestControllerAdvice.java
  src/main/java/com/fasttime/domain/report/exception/AlreadyDeletedPostException.java
  src/main/java/com/fasttime/domain/report/exception/DuplicateReportException.java
  src/main/java/com/fasttime/domain/report/service/ReportService.java
  src/main/java/com/fasttime/global/exception/ApplicationException.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/java/com/fasttime/global/exception/GlobalExceptionRestAdvice.java
  src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
  src/test/java/com/fasttime/domain/post/unit/service/PostCommandServiceTest.java
  src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
Labels: 🚧 refactoring

#98 [refactor] Admin 회원가입 로직 수정
  src/main/java/com/fasttime/domain/member/controller/AdminController.java
  src/main/java/com/fasttime/domain/member/dto/request/LoginRequestDTO.java
  src/main/java/com/fasttime/domain/member/entity/AdminEmail.java
  src/main/java/com/fasttime/domain/member/repository/AdminEmailRepository.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/main/java/com/fasttime/global/config/WebConfig.java
Labels: 🛠️ feature, 🚧 refactoring

#104 [fix] LoginCheckInterceptor.java NPE 수정
  src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java
Labels: 👷‍♂️fix

#105 [fix] fc_member확인 기능을 email에 적용한다.
  src/main/java/com/fasttime/domain/member/controller/EmailController.java
  src/main/java/com/fasttime/domain/member/controller/MemberController.java
  src/test/java/com/fasttime/domain/member/controller/EmailControllerTest.java
Labels: 🛠️ feature, 👷‍♂️fix

#107 [refactor] BindingResult 삭제 및 orElseThrow() 사용
  src/main/java/com/fasttime/domain/member/controller/AdminController.java
  src/main/java/com/fasttime/domain/member/controller/MemberController.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/main/java/com/fasttime/domain/member/service/MemberService.java
Labels: 🚧 refactoring

#108 [fix] 누락된 login interceptor `PathPattern` 추가
  src/main/java/com/fasttime/global/config/WebConfig.java
Labels: 👷‍♂️fix

#109 [feature] 게시글 댓글 갯수 쿼리 기능 추가
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/main/java/com/fasttime/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/fasttime/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/fasttime/domain/post/service/PostQueryService.java
Labels: 🛠️ feature

#110 [refacor] 게시글 API `HttpSession` 사용
  src/main/java/com/fasttime/domain/post/controller/PostController.java
  src/main/java/com/fasttime/domain/post/dto/controller/request/PostCreateRequestDto.java
  src/test/java/com/fasttime/domain/post/docs/PostControllerDocsTest.java
  src/test/java/com/fasttime/domain/post/unit/controller/PostControllerTest.java
Labels: 🚧 refactoring
