Repository boocam-project/FastTime-backend, pull requests merged in 2023-08, with the labels that each got.

#5 사용자는 게시글을 작성할 수 있다.
  src/main/java/com/fasttime/domain/post/controller/PostController.java
  src/main/java/com/fasttime/domain/post/dto/controller/request/PostCreateRequestDto.java
  src/main/java/com/fasttime/domain/post/dto/usecase/request/PostCreateServiceDto.java
  src/main/java/com/fasttime/domain/post/dto/usecase/response/PostResponseDto.java
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/main/java/com/fasttime/domain/post/entity/PostContent.java
  src/main/java/com/fasttime/domain/post/repository/PostRepository.java
  src/main/java/com/fasttime/domain/post/service/PostService.java
  src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
  src/test/java/com/fasttime/domain/post/unit/service/PostServiceTest.java
Labels: 🛠️ feature

#7 게시글 엔티티 변경
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/main/java/com/fasttime/domain/post/entity/ReportStatus.java
  src/main/java/com/fasttime/domain/post/service/PostService.java
  src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
Labels: 🛠️ feature, 🚧 refactoring

#8 테스트 환경을 구축한다.
  build.gradle
  src/main/java/com/fasttime/domain/post/dto/usecase/response/PostResponseDto.java
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/test/java/com/fasttime/domain/post/unit/service/PostServiceTest.java
  src/test/resources/application.yaml
Labels: 🛠️ feature, 🚧 refactoring

#18 [fix] 오타를 수정한다.
  src/main/java/com/fasttime/domain/post/controller/PostController.java
  src/main/java/com/fasttime/domain/post/dto/controller/request/PostCreateRequestDto.java
  src/main/java/com/fasttime/domain/post/dto/controller/request/PostUpdateRequestDto.java
  src/main/java/com/fasttime/domain/post/dto/service/request/PostCreateServiceDto.java
  src/main/java/com/fasttime/domain/post/dto/service/request/PostUpdateServiceDto.java
  src/main/java/com/fasttime/domain/post/dto/service/response/PostListResponseDto.java
  src/main/java/com/fasttime/domain/post/dto/service/response/PostResponseDto.java
  src/main/java/com/fasttime/domain/post/service/PostCommandService.java
  src/main/java/com/fasttime/domain/post/service/PostQueryService.java
  src/main/java/com/fasttime/domain/post/service/PostService.java
  src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
  src/test/java/com/fasttime/domain/post/unit/service/PostCommandServiceTest.java
Labels: 👷‍♂️fix

#17 github-action을 등록한다.
  .github/ISSUE_TEMPLATE/basic-issue-template.md
  .github/workflows/gradle.yml
Labels: 🛠️ feature

#19 ResponseDTO 생성
  src/main/java/com/fasttime/global/util/ResponseDTO.java
Labels: 🛠️ feature

#21 댓글 컨트롤러에서 ResponseDTO를 사용하도록 수정
  src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
  src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java
  src/test/java/com/fasttime/domain/comment/controller/CommentRestControllerTest.java
Labels: 🚧 refactoring

#23 [feature] 게시글 신고를 할 수 있다. #22
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/main/java/com/fasttime/domain/post/entity/ReportStatus.java
  src/main/java/com/fasttime/global/common/BaseTimeEntity.java
  src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
Labels: 🛠️ feature

#20 로그인, 로그아웃, 세션 기능 구현
  build.gradle
  src/main/java/com/fasttime/domain/member/controller/EmailController.java
  src/main/java/com/fasttime/domain/member/controller/EmailControllerAdvice.java
  src/main/java/com/fasttime/domain/member/controller/MemberController.java
  src/main/java/com/fasttime/domain/member/controller/MemberControllerAdvice.java
  src/main/java/com/fasttime/domain/member/dto/request/LoginRequestDTO.java
  src/main/java/com/fasttime/domain/member/repository/MemberRepository.java
  src/main/java/com/fasttime/domain/member/request/CodeRequest.java
  src/main/java/com/fasttime/domain/member/request/RePasswordRequest.java
  src/main/java/com/fasttime/domain/member/response/MemberResponse.java
  src/main/java/com/fasttime/domain/member/service/EmailService.java
  src/main/java/com/fasttime/domain/member/service/MemberService.java
  src/main/java/com/fasttime/global/config/PasswordEncoderConfig.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/config/WebConfig.java
  src/main/java/com/fasttime/global/interceptor/AdminCheckInterceptor.java
  src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java
  src/main/resources/.env
  src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
  src/test/java/com/fasttime/domain/member/service/MemberServiceTestForAuto.java
Labels: 🛠️ feature

#27 [Fix] Advice 재구현
  src/main/java/com/fasttime/domain/member/controller/MemberControllerAdvice.java
  src/main/java/com/fasttime/domain/member/service/MemberService.java
  src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
Labels: 🐞 bug, 👷‍♂️fix

#24 게시글을 삭제할 수 있다.
  src/main/java/com/fasttime/domain/post/dto/service/request/PostDeleteServiceDto.java
  src/main/java/com/fasttime/domain/post/entity/Post.java
  src/main/java/com/fasttime/domain/post/service/PostCommandService.java
  src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
  src/test/java/com/fasttime/domain/post/unit/service/PostCommandServiceTest.java
Labels: 🛠️ feature

#32 예외처리를 리팩토링 한다.
  src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java
  src/main/java/com/fasttime/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/fasttime/domain/comment/exception/NotFoundException.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/main/java/com/fasttime/domain/member/controller/MemberControllerAdvice.java
  src/main/java/com/fasttime/domain/member/exception/UserNotFoundException.java
  src/main/java/com/fasttime/domain/post/exception/NotPostWriterException.java
  src/main/java/com/fasttime/domain/post/exception/PostNotFoundException.java
  src/main/java/com/fasttime/domain/post/service/PostCommandService.java
  src/main/java/com/fasttime/global/exception/ApplicationException.java
  src/main/java/com/fasttime/global/exception/GlobalExceptionRestAdvice.java
  src/main/java/com/fasttime/global/util/ResponseDTO.java
  src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java
  src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
Labels: 🚧 refactoring

#29 댓글 조회 기능 추가 구현
  src/main/java/com/fasttime/domain/comment/repository/CommentRepository.java
  src/main/java/com/fasttime/domain/comment/service/CommentService.java
  src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java
Labels: 🛠️ feature

#25 신고 기능 구현
  src/main/java/com/fasttime/domain/report/contoller/ReportRestController.java
  src/main/java/com/fasttime/domain/report/contoller/ReportRestControllerAdvice.java
  src/main/java/com/fasttime/domain/report/dto/ReportDTO.java
  src/main/java/com/fasttime/domain/report/dto/request/CreateReportRequest.java
  src/main/java/com/fasttime/domain/report/entity/Report.java
  src/main/java/com/fasttime/domain/report/exception/AlreadyDeletedPostException.java
  src/main/java/com/fasttime/domain/report/exception/DuplicateReportException.java
  src/main/java/com/fasttime/domain/report/repository/ReportRepository.java
  src/main/java/com/fasttime/domain/report/service/ReportService.java
  src/test/java/com/fasttime/domain/report/controller/ReportRestControllerTest.java
  src/test/java/com/fasttime/domain/report/entity/ReportTest.java
  src/test/java/com/fasttime/domain/report/service/ReportServiceTest.java
Labels: 🛠️ feature, ❗️suggestion

#31 Admin 기능 구현
  src/main/java/com/fasttime/domain/member/controller/AdminController.java
  src/main/java/com/fasttime/domain/member/controller/AdminControllerAdvice.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/main/java/com/fasttime/domain/post/repository/PostRepository.java
  src/main/java/com/fasttime/global/interceptor/AdminCheckInterceptor.java
  src/test/java/com/fasttime/domain/member/controller/AdminControllerTest.java
  src/test/java/com/fasttime/domain/member/service/AdminServiceTest.java
  src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
Labels: 🛠️ feature
