Repository boocam-project/FastTime-backend, pull requests merged in 2024-04, with the labels that each got.

#234 [fix] @Qualifier로 주입해야 할 빈 객체 한정
  src/main/java/com/fasttime/global/config/BatchConfig.java
Labels: 🐞 bug, 👷‍♂️fix

#231 [Feature] 인증 로직을 개발한다
  build/generated/sources/annotationProcessor/java/main/com/fasttime/domain/certification/entity/QBootCamp.java
  build/generated/sources/annotationProcessor/java/main/com/fasttime/domain/certification/entity/QCertification.java
  src/docs/asciidoc/certification/certification-api.adoc
  src/main/java/com/fasttime/domain/certification/controller/CertificationController.java
  src/main/java/com/fasttime/domain/certification/dto/request/CertificationRequestDTO.java
  src/main/java/com/fasttime/domain/certification/dto/request/RejectionRequestDTO.java
  src/main/java/com/fasttime/domain/certification/dto/request/WithdrawalRequestDTO.java
  src/main/java/com/fasttime/domain/certification/dto/response/AllCertificationResponseDTO.java
  src/main/java/com/fasttime/domain/certification/dto/response/ApproveResponseDTO.java
  src/main/java/com/fasttime/domain/certification/dto/response/CertificationResponseDTO.java
  src/main/java/com/fasttime/domain/certification/dto/response/MyCertificationResponseDTO.java
  src/main/java/com/fasttime/domain/certification/entity/BootCamp.java
  src/main/java/com/fasttime/domain/certification/entity/Certification.java
  src/main/java/com/fasttime/domain/certification/entity/CertificationStatus.java
  src/main/java/com/fasttime/domain/certification/exception/CertificationBadRequestException.java
  src/main/java/com/fasttime/domain/certification/exception/CertificationNotFoundException.java
  src/main/java/com/fasttime/domain/certification/exception/CertificationUnAuthException.java
  src/main/java/com/fasttime/domain/certification/repository/BootCampRepository.java
  src/main/java/com/fasttime/domain/certification/repository/CertificationRepository.java
  src/main/java/com/fasttime/domain/certification/service/CertificationService.java
  src/main/java/com/fasttime/domain/member/entity/Member.java
  src/main/java/com/fasttime/domain/member/service/AdminService.java
  src/main/java/com/fasttime/domain/review/entity/Review.java
  src/main/java/com/fasttime/domain/review/service/ReviewService.java
  src/main/java/com/fasttime/global/batch/scheduler/BatchScheduler.java
  src/main/java/com/fasttime/global/batch/tasklet/DeleteCertificationsTasklet.java
  src/main/java/com/fasttime/global/config/BatchConfig.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/resources/db/migration/V23__Add_certification_table.sql
  src/test/java/com/fasttime/domain/certification/docs/CertificationControllerDocsTest.java
  src/test/java/com/fasttime/domain/certification/unit/entity/BootCampTest.java
  src/test/java/com/fasttime/domain/certification/unit/entity/CertificationTest.java
  src/test/java/com/fasttime/domain/certification/unit/repository/BootCampRepositoryTest.java
  src/test/java/com/fasttime/domain/certification/unit/repository/CertificationRepositoryTest.java
  src/test/java/com/fasttime/domain/certification/unit/service/CertificationServiceTest.java
  src/test/java/com/fasttime/domain/member/unit/controller/MemberControllerTest.java
  src/test/java/com/fasttime/domain/review/unit/entity/ReviewTest.java
  src/test/java/com/fasttime/domain/review/unit/service/ReviewServiceTest.java
Labels: 🛠️ feature, 👷‍♂️fix

#237 [Feat] index.adoc에 certification 링크 추가
  src/docs/asciidoc/index.adoc
Labels: 🛠️ feature

#201 자기소개서 기능 개발
  src/main/java/com/fasttime/domain/resume/controller/ResumeController.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeDeleteServiceRequest.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeRequestDto.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeResponseDto.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeUpdateRequest.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeUpdateServiceRequest.java
  src/main/java/com/fasttime/domain/resume/entity/Resume.java
  src/main/java/com/fasttime/domain/resume/exception/NoResumeWriterException.java
  src/main/java/com/fasttime/domain/resume/exception/ResumeNotFoundException.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeRepository.java
  src/main/java/com/fasttime/domain/resume/service/ResumeService.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/resources/db/migration/V24__Add_Column_Resume_table.sql
  src/test/java/com/fasttime/domain/resume/unit/entity/ResumeTest.java
  src/test/java/com/fasttime/domain/resume/unit/service/ResumeServiceTest.java
Labels: 🛠️ feature

#239 [Feature] Email기능 REST Docs 문서화
  src/docs/asciidoc/certification/certification-api.adoc
  src/docs/asciidoc/email/email-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/fasttime/domain/member/controller/EmailController.java
  src/test/java/com/fasttime/domain/certification/docs/CertificationControllerDocsTest.java
  src/test/java/com/fasttime/domain/member/docs/EmailControllerDocsTest.java
Labels: 📕 document, 👷‍♂️fix

#236 [feat] AOP를 적용한 SSE 기반 알림 기능 구현
  src/main/java/com/fasttime/domain/notification/annotation/NeedNotification.java
  src/main/java/com/fasttime/domain/notification/aop/NotificationAspect.java
  src/main/java/com/fasttime/domain/notification/aop/proxy/NotificationInfo.java
  src/main/java/com/fasttime/domain/notification/controller/NotificationController.java
  src/main/java/com/fasttime/domain/notification/dto/response/NotificationResponseDto.java
  src/main/java/com/fasttime/domain/notification/entity/Notification.java
  src/main/java/com/fasttime/domain/notification/entity/NotificationType.java
  src/main/java/com/fasttime/domain/notification/exception/SseConnectionFailedException.java
  src/main/java/com/fasttime/domain/notification/exception/UnsupportedDataTypeForNotificationSendingException.java
  src/main/java/com/fasttime/domain/notification/repository/EmitterRepository.java
  src/main/java/com/fasttime/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/fasttime/domain/notification/repository/NotificationRepository.java
  src/main/java/com/fasttime/domain/notification/service/NotificationService.java
  src/main/java/com/fasttime/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/resources/db/migration/V23__Add_notification_table.sql
  src/test/java/com/fasttime/domain/notification/unit/controller/NotificationControllerTest.java
  src/test/java/com/fasttime/domain/notification/unit/entity/NotificationTest.java
  src/test/java/com/fasttime/domain/notification/unit/repository/EmitterRepositoryImplTest.java
  src/test/java/com/fasttime/domain/notification/unit/service/NotificationServiceImplTest.java
  src/test/java/com/fasttime/util/ControllerUnitTestSupporter.java
Labels: 📕 document, 🛠️ feature, 🚧 refactoring

#238 [feat] 스터디 게시판 CRUD 기능을 추가한다.
  src/main/java/com/fasttime/domain/study/controller/StudyController.java
  src/main/java/com/fasttime/domain/study/dto/StudyCreateRequest.java
  src/main/java/com/fasttime/domain/study/dto/StudyPageRequestService.java
  src/main/java/com/fasttime/domain/study/dto/StudyPageResponse.java
  src/main/java/com/fasttime/domain/study/dto/StudyResponse.java
  src/main/java/com/fasttime/domain/study/dto/StudyUpdateRequest.java
  src/main/java/com/fasttime/domain/study/entity/Category.java
  src/main/java/com/fasttime/domain/study/entity/Study.java
  src/main/java/com/fasttime/domain/study/entity/StudyCategory.java
  src/main/java/com/fasttime/domain/study/entity/StudyState.java
  src/main/java/com/fasttime/domain/study/exception/CategoryNotFoundException.java
  src/main/java/com/fasttime/domain/study/exception/NotStudyWriterException.java
  src/main/java/com/fasttime/domain/study/exception/StudyNotFoundException.java
  src/main/java/com/fasttime/domain/study/repository/CategoryRepository.java
  src/main/java/com/fasttime/domain/study/repository/StudyCategoryRepository.java
  src/main/java/com/fasttime/domain/study/repository/StudyRepository.java
  src/main/java/com/fasttime/domain/study/repository/StudyRepositoryCustom.java
  src/main/java/com/fasttime/domain/study/repository/StudyRepositoryImpl.java
  src/main/java/com/fasttime/domain/study/service/CategoryService.java
  src/main/java/com/fasttime/domain/study/service/StudyCategoryService.java
  src/main/java/com/fasttime/domain/study/service/StudyService.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/resources/db/migration/V24__Add_study_table.sql
  src/main/resources/db/migration/V25__Add_category_table.sql
  src/main/resources/db/migration/V26__Add_studyCategory_table.sql
Labels: 🛠️ feature

#246 [Feature] 자기소개서 게시판 조회
  src/main/java/com/fasttime/domain/resume/controller/ResumeController.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeResponseDto.java
  src/main/java/com/fasttime/domain/resume/dto/ResumesSearchRequest.java
  src/main/java/com/fasttime/domain/resume/exception/ResumeAlreadyDeletedException.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeCustomRepository.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeOrderBy.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeRepository.java
  src/main/java/com/fasttime/domain/resume/service/ResumeService.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/test/java/com/fasttime/domain/resume/unit/repository/ResumeRepositoryTest.java
  src/test/java/com/fasttime/domain/resume/unit/service/ResumeServiceTest.java
Labels: 🛠️ feature

#247 [fix] flyway 오류 수정
  src/main/resources/db/migration/V26__Add_notification_table.sql
  src/main/resources/db/migration/V27__Add_study_table.sql
  src/main/resources/db/migration/V28__Add_studyCategory_table.sql
Labels: 🐞 bug

#253 [feat] 스터디 CRUD, 카테고리 조회 API docs test를 추가한다.
  build.gradle
  src/docs/asciidoc/category/category-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/study/study-api.adoc
  src/main/java/com/fasttime/domain/study/controller/CategoryController.java
  src/main/java/com/fasttime/domain/study/controller/StudyController.java
  src/main/java/com/fasttime/domain/study/dto/CategoryResponse.java
  src/main/java/com/fasttime/domain/study/dto/StudyCreateRequest.java
  src/main/java/com/fasttime/domain/study/dto/StudyUpdateRequest.java
  src/main/java/com/fasttime/domain/study/exception/StudyDeleteException.java
  src/main/java/com/fasttime/domain/study/repository/StudyRepositoryImpl.java
  src/main/java/com/fasttime/domain/study/service/CategoryService.java
  src/main/java/com/fasttime/domain/study/service/StudyService.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/test/java/com/fasttime/docs/RestDocsSupport.java
  src/test/java/com/fasttime/domain/study/docs/CategoryControllerTest.java
  src/test/java/com/fasttime/domain/study/docs/StudyControllerTest.java
Labels: 📕 document, 🛠️ feature

#263 [refactor] REST Docs 오타 수정
  src/docs/asciidoc/index.adoc
Labels: 👷‍♂️fix
