Repository boocam-project/FastTime-backend, pull requests merged in 2024-05, with the labels that each got.

#257 [Feature] 자기소개서 좋아요 & 조회수 기능 추가
  src/main/java/com/fasttime/domain/resume/controller/ResumeController.java
  src/main/java/com/fasttime/domain/resume/dto/LikeResumeRequest.java
  src/main/java/com/fasttime/domain/resume/entity/Like.java
  src/main/java/com/fasttime/domain/resume/entity/Resume.java
  src/main/java/com/fasttime/domain/resume/exception/AlreadyExistsResumeLikeException.java
  src/main/java/com/fasttime/domain/resume/exception/UnauthorizedAccessLikeException.java
  src/main/java/com/fasttime/domain/resume/repository/LikeRepository.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeCustomRepository.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/resume/service/ResumeService.java
  src/main/java/com/fasttime/global/batch/scheduler/BatchScheduler.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateResumeViewCountTasklet.java
  src/main/java/com/fasttime/global/config/BatchConfig.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/resources/db/migration/V25_Add_Resume_Table.sql
  src/test/java/com/fasttime/domain/resume/unit/service/ResumeServiceTest.java
Labels: 🛠️ feature

#266 [Refactor] 리뷰도메인 캐시 재설정
  src/main/java/com/fasttime/domain/review/service/ReviewService.java
Labels: 👷‍♂️fix

#262 [feat] 스터디 모집글 댓글 CRUD 기능을 추가한다.
  src/docs/asciidoc/study_comment/studyComment-api.adoc
  src/main/java/com/fasttime/domain/study/service/StudyService.java
  src/main/java/com/fasttime/domain/studyComment/controller/StudyCommentController.java
  src/main/java/com/fasttime/domain/studyComment/dto/request/CreateStudyCommentRequestDTO.java
  src/main/java/com/fasttime/domain/studyComment/dto/request/GetStudyCommentsRequestDTO.java
  src/main/java/com/fasttime/domain/studyComment/dto/request/StudyCommentPageRequestDTO.java
  src/main/java/com/fasttime/domain/studyComment/dto/request/UpdateStudyCommentRequestDTO.java
  src/main/java/com/fasttime/domain/studyComment/dto/response/StudyCommentListResponseDTO.java
  src/main/java/com/fasttime/domain/studyComment/dto/response/StudyCommentResponseDTO.java
  src/main/java/com/fasttime/domain/studyComment/entity/StudyComment.java
  src/main/java/com/fasttime/domain/studyComment/exception/NotStudyCommentAuthorException.java
  src/main/java/com/fasttime/domain/studyComment/exception/StudyCommentNotFoundException.java
  src/main/java/com/fasttime/domain/studyComment/repository/StudyCommentCustomRepository.java
  src/main/java/com/fasttime/domain/studyComment/repository/StudyCommentCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/studyComment/repository/StudyCommentRepository.java
  src/main/java/com/fasttime/domain/studyComment/service/StudyCommentService.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/java/com/fasttime/global/util/WebDriverUtil.java
  src/main/resources/db/migration/V30__Add_studyComment_table.sql
  src/test/java/com/fasttime/domain/studyComment/docs/StudyCommentControllerDocsTest.java
  src/test/java/com/fasttime/domain/studyComment/unit/entity/StudyCommentTest.java
  src/test/java/com/fasttime/domain/studyComment/unit/service/StudyCommentServiceTest.java
Labels: 📕 document, 🛠️ feature, 🚧 refactoring

#268 [Feat] 자기소개서 REST Docs 문서화
  .env.sample
  .gitmodules
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/resume/resume-api.adoc
  src/main/java/com/fasttime/domain/resume/controller/ResumeController.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeResponseDto.java
  src/test/java/com/fasttime/domain/resume/docs/ResumeControllerDocsTest.java
Labels: 📕 document, 🛠️ feature, 🚧 refactoring

#265 [Feature] 우수 자기소개서 기능 개발
  src/main/java/com/fasttime/domain/resume/controller/ResumeController.java
  src/main/java/com/fasttime/domain/resume/dto/LikeResumeRequest.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeDeleteServiceRequest.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeRequestDto.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeUpdateRequest.java
  src/main/java/com/fasttime/domain/resume/dto/ResumeUpdateServiceRequest.java
  src/main/java/com/fasttime/domain/resume/dto/ResumesSearchRequest.java
  src/main/java/com/fasttime/domain/resume/entity/Resume.java
  src/main/java/com/fasttime/domain/resume/entity/ViewCount.java
  src/main/java/com/fasttime/domain/resume/exception/AlreadyExistsResumeLikeException.java
  src/main/java/com/fasttime/domain/resume/exception/ResumeAlreadyDeletedException.java
  src/main/java/com/fasttime/domain/resume/infra/GetResumeEvent.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeCustomRepository.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/resume/repository/ResumeRepository.java
  src/main/java/com/fasttime/domain/resume/repository/ViewCountRepository.java
  src/main/java/com/fasttime/domain/resume/service/ResumeEventListener.java
  src/main/java/com/fasttime/domain/resume/service/ResumeService.java
  src/main/java/com/fasttime/domain/resume/service/ViewCountService.java
  src/main/java/com/fasttime/global/batch/scheduler/BatchScheduler.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateResumeViewCountTasklet.java
  src/main/resources/db/migration/V32_Add_Resume_Table.sql
  src/test/java/com/fasttime/domain/resume/unit/repository/ResumeRepositoryTest.java
  src/test/java/com/fasttime/domain/resume/unit/service/ResumeServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring

#270 [Fix] Flyway 스크립트를 통한 Spring Batch 테이블 추가
  src/main/resources/db/migration/V33__Add_Batch_Tables.sql
Labels: 👷‍♂️fix
