Repository boocam-project/FastTime-backend, pull requests merged in 2024-03, with the labels that each got.

#183 [feat] 대외 활동, 공모전 기능 개발
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/reference/reference-api.adoc
  src/main/java/com/fasttime/domain/reference/controller/CrawlingController.java
  src/main/java/com/fasttime/domain/reference/controller/ReferenceController.java
  src/main/java/com/fasttime/domain/reference/dto/request/ReferencePageRequestDto.java
  src/main/java/com/fasttime/domain/reference/dto/request/ReferenceSearchRequestDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/ActivityPageResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/ActivityResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/CompetitionPageResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/CompetitionResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/ReferenceResponseDto.java
  src/main/java/com/fasttime/domain/reference/entity/Activity.java
  src/main/java/com/fasttime/domain/reference/entity/Competition.java
  src/main/java/com/fasttime/domain/reference/entity/RecruitmentStatus.java
  src/main/java/com/fasttime/domain/reference/entity/SearchCrawling.java
  src/main/java/com/fasttime/domain/reference/exception/ActivityNotFountException.java
  src/main/java/com/fasttime/domain/reference/exception/CompetitionNotFountException.java
  src/main/java/com/fasttime/domain/reference/repository/ActivityCustomRepository.java
  src/main/java/com/fasttime/domain/reference/repository/ActivityCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/reference/repository/ActivityRepository.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionCustomRepository.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionRepository.java
  src/main/java/com/fasttime/domain/reference/service/CrawlingService.java
  src/main/java/com/fasttime/domain/reference/service/ReferenceService.java
  src/main/java/com/fasttime/domain/reference/service/usecase/ReferenceServiceUseCase.java
  src/main/java/com/fasttime/global/config/QueryDslConfig.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/java/com/fasttime/global/util/QueryDslUtil.java
  src/main/java/com/fasttime/global/util/WebDriverUtil.java
  src/main/resources/db/migration/V19__Update_Column_memeber_table.sql
  src/main/resources/db/migration/V20__Update_Column_tag_table.sql
  src/main/resources/db/migration/V21__Add_activity_table.sql
  src/main/resources/db/migration/V22__Add_competition_table.sql
  src/test/java/com/fasttime/domain/reference/docs/ReferenceControllerDocsTest.java
  src/test/java/com/fasttime/domain/reference/unit/repository/ActivityRepositoryTest.java
  src/test/java/com/fasttime/domain/reference/unit/repository/CompetitionRepositoryTest.java
  src/test/java/com/fasttime/domain/reference/unit/service/ReferenceServiceTest.java
  src/test/java/com/fasttime/global/config/JpaTestConfig.java
  src/test/java/com/fasttime/global/config/QueryDslTestConfig.java
Labels: 🛠️ feature

#197 flyway 수정
  src/main/resources/db/migration/V19__Update_Column_memeber_table.sql
  src/main/resources/db/migration/V20__Update_Column_tag_table.sql
Labels: 🐞 bug, 👷‍♂️fix

#196 코드리뷰 자동화 구현
  .github/workflows/cr.yml
Labels: 🛠️ feature

#199 Batch 기능을 사용하여, 레퍼런스 크롤링 및 상태 변경을 자동화 한다.
  src/main/java/com/fasttime/domain/reference/repository/ActivityCustomRepository.java
  src/main/java/com/fasttime/domain/reference/repository/ActivityCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionCustomRepository.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/reference/service/CrawlingService.java
  src/main/java/com/fasttime/global/batch/scheduler/BatchScheduler.java
  src/main/java/com/fasttime/global/batch/tasklet/DeleteOldReviewsTasklet.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateActivityStatusTasklet.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateCompetitionStatusTasklet.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateDoneActivityTasklet.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateDoneCompetitionTasklet.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateNewActivityTasklet.java
  src/main/java/com/fasttime/global/batch/tasklet/UpdateNewCompetitionTasklet.java
  src/main/java/com/fasttime/global/config/BatchConfig.java
  src/test/java/com/fasttime/domain/review/unit/service/BatchSchedulerTest.java
Labels: 🛠️ feature

#203 [fix] 이메일 기능 401에러 수정
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
Labels: 👷‍♂️fix
