Repository boocam-project/FastTime-backend, pull requests merged in 2024-02, with the labels that each got.

#182 [feat] 대외 활동, 공모전 API 개발
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/reference/reference-api.adoc
  src/main/java/com/fasttime/domain/reference/controller/ReferenceController.java
  src/main/java/com/fasttime/domain/reference/dto/request/ReferencePageRequestDto.java
  src/main/java/com/fasttime/domain/reference/dto/request/ReferenceSearchRequestDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/ActivityPageResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/ActivityResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/CompetitionPageResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/CompetitionResponseDto.java
  src/main/java/com/fasttime/domain/reference/dto/response/ReferenceResponseDto.java
  src/main/java/com/fasttime/domain/reference/exception/ActivityNotFountException.java
  src/main/java/com/fasttime/domain/reference/exception/CompetitionNotFountException.java
  src/main/java/com/fasttime/domain/reference/repository/ActivityCustomRepository.java
  src/main/java/com/fasttime/domain/reference/repository/ActivityCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/reference/repository/ActivityRepository.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionCustomRepository.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionCustomRepositoryImpl.java
  src/main/java/com/fasttime/domain/reference/repository/CompetitionRepository.java
  src/main/java/com/fasttime/domain/reference/service/ReferenceService.java
  src/main/java/com/fasttime/domain/reference/service/usecase/ReferenceServiceUseCase.java
  src/main/java/com/fasttime/global/config/QueryDslConfig.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/java/com/fasttime/global/util/QueryDslUtil.java
  src/main/resources/db/migration/V14__Add_Column_memeber_table.sql
  src/main/resources/db/migration/V15__Add_activity_table.sql
  src/main/resources/db/migration/V16__Add_competition_table.sql
  src/test/java/com/fasttime/domain/reference/docs/ReferenceControllerDocsTest.java
  src/test/java/com/fasttime/domain/reference/unit/repository/ActivityRepositoryTest.java
  src/test/java/com/fasttime/domain/reference/unit/repository/CompetitionRepositoryTest.java
  src/test/java/com/fasttime/domain/reference/unit/service/ReferenceServiceTest.java
  src/test/java/com/fasttime/global/config/JpaTestConfig.java
  src/test/java/com/fasttime/global/config/QueryDslTestConfig.java
Labels: 🛠️ feature

#179 [Feature] 태그 등록문제 해결 및 리뷰 조회 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/review/review-api.adoc
  src/main/java/com/fasttime/domain/member/repository/MemberRepository.java
  src/main/java/com/fasttime/domain/review/controller/ReviewController.java
  src/main/java/com/fasttime/domain/review/dto/response/BootcampReviewSummaryDTO.java
  src/main/java/com/fasttime/domain/review/dto/response/TagSummaryDTO.java
  src/main/java/com/fasttime/domain/review/entity/Review.java
  src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
  src/main/java/com/fasttime/domain/review/entity/Tag.java
  src/main/java/com/fasttime/domain/review/exception/BootCampNotFoundException.java
  src/main/java/com/fasttime/domain/review/repository/ReviewRepository.java
  src/main/java/com/fasttime/domain/review/repository/ReviewTagRepository.java
  src/main/java/com/fasttime/domain/review/service/ReviewService.java
  src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
  src/main/java/com/fasttime/global/exception/ErrorCode.java
  src/main/resources/db/migration/V15__Add_Column_tag_table.sql
  src/test/java/com/fasttime/domain/review/docs/ReviewControllerDocsTest.java
  src/test/java/com/fasttime/domain/review/unit/controller/ReviewControllerTest.java
  src/test/java/com/fasttime/domain/review/unit/entity/ReviewTest.java
  src/test/java/com/fasttime/domain/review/unit/entity/TagTest.java
  src/test/java/com/fasttime/domain/review/unit/service/ReviewServiceTest.java
  src/test/java/com/fasttime/util/ControllerUnitTestSupporter.java
Labels: 🛠️ feature, 🚧 refactoring, 👷‍♂️fix

#187 [docs] 리드미 작성
  README.md
  src/main/resources/images/architecture.png
  src/main/resources/images/erd.png
  src/main/resources/images/logo.png
Labels: 📕 document

#184 [Feature] BootCamp 테이블 분리 및 리뷰조회 응답 수정
  src/main/java/com/fasttime/domain/bootcamp/entity/BootCamp.java
  src/main/java/com/fasttime/domain/bootcamp/repository/BootCampRepository.java
  src/main/java/com/fasttime/domain/member/entity/Member.java
  src/main/java/com/fasttime/domain/member/repository/MemberRepository.java
  src/main/java/com/fasttime/domain/review/dto/request/ReviewRequestDTO.java
  src/main/java/com/fasttime/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/com/fasttime/domain/review/entity/Review.java
  src/main/java/com/fasttime/domain/review/repository/ReviewRepository.java
  src/main/java/com/fasttime/domain/review/repository/ReviewTagRepository.java
  src/main/java/com/fasttime/domain/review/service/ReviewService.java
  src/main/resources/db/migration/V16__Add_bootcamp_table.sql
  src/main/resources/db/migration/V17__Update_Column_member_table.sql
  src/main/resources/db/migration/V18__Update_Column_review_table.sql
  src/test/java/com/fasttime/domain/review/docs/ReviewControllerDocsTest.java
  src/test/java/com/fasttime/domain/review/unit/controller/ReviewControllerTest.java
  src/test/java/com/fasttime/domain/review/unit/entity/ReviewTest.java
  src/test/java/com/fasttime/domain/review/unit/service/ReviewServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring
